### PR TITLE
[WIP] ARM: Add some inline assembly for bigint

### PR DESCRIPTION
**Pull request by redstar**
Implements the internal interface in ARM assembly.

### CODE REVIEW

**Comment by redstar** [comment]
@smolt @joakim-noah Is this useful? For sure I need to add loop unrolling.

**Comment by joakim-noah** [comment]
Looks like it might be, but its release tests assert at line 90 on Android/ARM and it causes test failures in other dependent modules like `std.bigint` too (at line 236 in ltsmaster).

**Comment by redstar** [comment]
@joakim-noah Thanks for trying. I try to correct the failures. (Didn't see them yesterday on my arm box but I made some more changes this morning.)

**Comment by JohanEngelen** [comment]
@redstar Just a suggestion. Isn't it possible to do this in IR? Perhaps then you get the optimization for free. Or can LLVM also optimize the asm?

**Comment by redstar** [comment]
IR is no better than D. With D and IR you have to use the overflow intrinsics which leads to horrible codegen. I tried it with x86_64 and it is only marginable better than the D version.

**Comment by smolt** [comment]
Any opportunity to write assembly code should be taken advantage of :smile:

I am on vacation, would like to spend time on on this when I am worn out.

**Comment by JohanEngelen** [comment]
> Any opportunity to write assembly code should be taken advantage of

Haha, indeed!
Thanks @redstar for increasing my ammunition in discussions about asm :)

Enjoy the snow @smolt .

**Comment by redstar** [comment]
The implemented functions now pass all tests, including `-O3 -release`. Currently measured speedup: `multibyteAddSub!('+')`: 2.2, `multibyteMul`: 1.4 and `multibyteMulAdd!('+')`: 1.2. There is still room for improvement.
To measure the timings I compiled the binary with: `ldc2 -release -O3 -singleobj -unittest -d-version=timings biguintarm.d biguintnoasm.d`.

**Comment by joakim-noah** [comment]
All tests now pass on Android/ARM when compiled in release mode, the new module's tests take 6 seconds to run.

**Comment by redstar** [comment]
@jpf91 Maybe this is interesting for gdc, too?

**Comment by jpf91** [comment]
That's certainly interesting, thanks for the ping :-)

Is the LDC inline ASM string and the constraint string GCC compatible? Then we could probably implement the `__asm` interface in gdc to provide a common inline ASM syntax for LDC and GDC. ping @ibuclaw

**Comment by redstar** [comment]
@jpf91 Unfortunately the constraint string is not GCC compatible. (The content is but not the syntax.) Maybe we can agree on some standard here?

**Comment by ibuclaw** [comment]
Does the constraints string match what the LLVM backend expects? Or is it specially handled in LDC?

**Comment by dnadlinger** [comment]
It is a backend thing.

**Comment by ibuclaw** [comment]
Then we should continue doing what is most natural for our respective backends. :-)

**Comment by redstar** [comment]
Merged in master now.

**Pull request closed without merging**
