### PR TITLE
Solaris unittest: fix formatTest for T.nan

### PR DESCRIPTION
**Pull request by nykytenko**
Fix std.format unittest AssertError.

### CODE REVIEW

**Comment by kinke** [comment]
Thanks. Could you please squash the two commits into one? Just in case: `git rebase -i HEAD~2` and set the latest commit to `f` (fixup).

**Comment by nykytenko** [comment]
> Could you please squash the two commits into one?

Done.

**Comment by kinke** [comment]
Hmm I'm not sure whether that's okay, or whether you should instead make sure Phobos does return a lowercase `nan` for Solaris too. So that Phobos formatting doesn't depend on platform/OS.

**Comment by kinke** [comment]
Yep, that's what is done for MSVC too: https://github.com/ldc-developers/phobos/blob/3c50c24a8e778fdc9d4a36f8e0a949403cbe6bf9/std/format.d#L1706

**Comment by dnadlinger** [comment]
Agreed, Phobos should have to deal with platform differences, not the user. IIRC we discussed this rather thoroughly upstream when the MSVC/MinGW ports came first along, and having Phobos work around platform differences was the wide consensus.

**Comment by nykytenko** [comment]
> Agreed, Phobos should have to deal with platform differences, not the user.

Maybe. 
Ok. I'm closing this PR.

**Pull request closed without merging**
