### PR TITLE
Make std.complex be like native type for optimization

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
ping @JohanEngelen

**Comment by dnadlinger** [comment]
No; this changes FP semantics. Can't do it in the general case.

**Comment by 9il** [comment]
This does not change FP semantics outside from this functions in general case. It is safe to add FMA instructions inside this functions.

**Comment by dnadlinger** [comment]
If this didn't change anything, why would you add the attributes in the first case?

**Comment by 9il** [comment]
1. Because it allows to optimize properly a function that use complex numbers if it has fast math too. Loops especially.
2. FMA instructions are optimization for complex numbers anyway. It would not be applied without this PR even if caller function has fast math

**Comment by kinke** [comment]
FMA may be okay, but `fastmath` also implies that the optimizer may assume there are no NaNs, no infs, and that it may replace divisions by multiplications (http://llvm.org/docs/LangRef.html#fast-math-flags) as well as reassociate etc., which definitely affect semantics.

**Comment by 9il** [comment]
> FMA may be okay, but fastmath also implies that the optimizer may assume there are no NaNs, no infs, and that it may replace divisions by multiplications (http://llvm.org/docs/LangRef.html#fast-math-flags) as well as reassociate etc., which definitely affect semantics.

This changes semantics only inside this functions. I don't see why it is wrong.

**Comment by kinke** [comment]
Well, it affects all unary and binary operators for example, as well as comparisons.

**Comment by 9il** [comment]
Mir migrate to native complex numbers. The reasons described here: http://forum.dlang.org/post/vcesltflvrteptvfiwzb@forum.dlang.org.

**Pull request closed without merging**
