### PR TITLE
std.math.log: use fyl2x asm instruction if available

### PR DESCRIPTION
**Pull request by Kozzi11**
This improve performance of std.math.log.

### CODE REVIEW

**Comment by dnadlinger** [comment]
So the LLVM codegen for `llvm.log` is suboptimal?

**Comment by Kozzi11** [comment]
Maybe
with fyl2x is little faster (9s) for my Intel CPU, and for my AMD cpu it takes 20sec less with fyl2x

http://dpaste.dzfl.pl/b049caf47498

**Comment by 9il** [comment]
> Maybe
> with fyl2x is little faster (9s) for my Intel CPU, and for my AMD cpu it takes 20sec less with fyl2x

This is valid only for 80bit reals. For 64bit  floats `fyl2x` is slower.

Please do not merge this PR!  On modern CPU LLVM will able to vectorize `llvm.log` and others.

**Comment by kinke** [comment]
[It's restricted to 80-bit reals.]

Some timings with LDC 1.11 on Ubuntu 18.04 and an Intel i5-3550 for:
```D
void main()
{
    real sum = 0;
    for (real r = 1e-9; r < 1; r += 1e-8)
         sum += log(r);
    import core.stdc.stdio;
    printf("result: %Lg\n", sum);
}
```

`std.math.log`: 2.9 secs (=> trampoline for `llvm_log`)
`ldc.intrinsics.llvm_log`: 2.74 secs (=> alias for C `logl`)
`core.math.yl2x`: 2.45 secs

=> ~15% runtime reduction on my box (**edit**: when called directly; with std.math wrapper, it'd be somewhat less).

**Comment by kinke** [comment]
We've been using it for a while now (only for x87 `real` obviously).

**Pull request closed without merging**
