### PR TITLE
Solaris: fix std.datetime:LocalTime.utcToTZ issue.

### PR DESCRIPTION
**Pull request by nykytenko**
Patch by @nykytenko, originally submitted at https://github.com/dlang/phobos/pull/5016.

### CODE REVIEW

**Comment by kinke** [comment]
Can you tell us what the status of LDC is on Solaris? Just to gauge whether it makes sense to backport this fix instead of waiting until we move to newer D versions.

**Comment by nykytenko** [comment]
LDC on Solaris work fine at now. We ported one relatively large project from linux to SmartOS and it working in production perfectly ~ 3 months. All critical bugs that I found, I fixed in earlier comments.
When you plan to move to newer D version? This bug is not time critical for us, but logs printed with only UTC time and it's uncomfortably.

**Comment by JohanEngelen** [comment]
Awesome :)

**Comment by JohanEngelen** [comment]
Merging, because it will be a while before we'll be at 2.073 ("three"!)

**Comment by JohanEngelen** [comment]
I've added this to release-1.1.0 too.

**Pull request merged**
