### PR TITLE
Use an alias instead of a wrapper function for intrinsic fabs()

### PR DESCRIPTION
**Pull request by p0nce**
Solves https://github.com/ldc-developers/ldc/issues/2182

### CODE REVIEW

**Comment by p0nce** [comment]
Workaround rather than solves

**Comment by kinke** [comment]
The other workaround is using `pragma(inline, true)`, used e.g. in `core.atomic`.

I plan on expanding this (aliasing) to most other intrinsic wrappers in the standard libs unless someone comes up with a good reason not to do so (documentation purposes, less precise error messages when using unsupported types etc.).

**Comment by p0nce** [comment]
This could create overload conflict if not restricted to floating point types.
For example if std.complex also defines `sqrt`

**Comment by kinke** [comment]
[Wrt. restricting it to the FP types, that'd be achievable via `alias fabs = llvm_fabs!float; alias fabs = llvm_fabs!double; ...`.]

Unfortunately, there are some tests making sure the std.math implementations are actual functions with an address. I don't share that opinion (should be simply as fast as possible; wrappers can be easily generated with mini templates if one really needs the function addresses). Anyway, the std.math functions wrapping an LLVM intrinsic are now all (at least last time I checked) decorated with `pragma(inline, true)`, so that they would be inlined with enabled cross-module inlining. In the meantime, these (and more) performance issues should be easily mitigated via LTO and the LTO default libs.

**Comment by p0nce** [comment]
Thanks. No problem for us we already need cross-module inlining so deeply it's always activated.

**Comment by kinke** [comment]
Did you give LTO on Win64 a try btw?

**Comment by p0nce** [comment]
Not yet but I can provide numbers tomorrow! What do you want?

**Comment by p0nce** [comment]
OK on an audio processing app involving a bit of everything, 50 samples.


```
LDC 1.12
Results:
 * minimum time: 167.6 ms => 31.75 x real-time
 * median  time: 168.7 ms => 31.54 x real-time
 * average time: 169.2 ms => 31.45 x real-time

Same with -flto=thin

Results:
 * minimum time: 162.2 ms => 32.80 x real-time
 * median  time: 162.7 ms => 32.70 x real-time
 * average time: 163.0 ms => 32.64 x real-time

Same with -flto=full

Results:
 * minimum time: 162.7 ms => 32.70 x real-time
 * median  time: 163.4 ms => 32.56 x real-time
 * average time: 164.5 ms => 32.35 x real-time
```

My conclusion is that for this particular work-load we can get a +3.3% improvement for free just enabling `-flto=thin`.
Our measurements were made a lot more precise since this summer: https://github.com/AuburnSounds/Dplug/commit/5388783f87c9548b2beae5bba22dafb6758d780d Previously it was unfortunately dependent on other processes, power management etc.
Currently we use LDC 1.8 as it won a speed shootout from 1.2 to 1.10

**Comment by kinke** [comment]
Nice to know it works - I've only tested some hello-world stuff. ;) - I guess you haven't tried with an additional `-defaultlib=druntime-ldc-lto,phobos2-ldc-lto`?

**Comment by p0nce** [comment]
**Windows + Thin LTO + LTO druntime/Phobos**
Same test with `-flto=thin -defaultlib=druntime-ldc-lto,phobos2-ldc-lto`.
```
Results:
 * minimum time: 162.5 ms => 32.74 x real-time
 * median  time: 163.3 ms => 32.59 x real-time
 * average time: 163.7 ms => 32.50 x real-time
```

However the test isn't exactly Phobos-heavy (perhaps C runtime heavy with transcendentals) so the most likely is that there is no change and we are under measurement noise. 

**Windows + Full LTO + LTO druntime/Phobos**
Same test with `-flto=full -defaultlib=druntime-ldc-lto,phobos2-ldc-lto`.
```
Results:
 * minimum time: 162.6 ms => 32.72 x real-time
 * median  time: 163.2 ms => 32.60 x real-time
 * average time: 163.5 ms => 32.54 x real-time
```
Same remark, this workload doesn't feature much Phobos/druntime in tight loops.

**Regarding speed-up**
It's best to ignore the "average time" since average of measurements are extremely sensible to outliers, so when I give you a speed-up it's a ratio of "minimum time".

Note that **debug-info is enabled** here! I've found that is doesn't affect speed. DUB command line is:
`dub build --build=release-debug --arch=x86_64 --compiler=ldc2 --combined`

**About correctness:**
It works and I haven't found a codegen problem, which is very interesting considering how much LTO can give problem with ICC. But here my test generates audio with low-amplitude noise so I'm not testing for exact bit-correct results (I'm checking for inaudible differences instead). Next time I will test for bit-correct results.

So the testing program actually also output:
```
Comparing batterie-reference.wav vs batterie-processed.wav

    =================================
        RMS difference = -80.99 dB
    =================================

 An opinion from the comparison program:
    "I doubt you may be able to hear it, but maybe do not take my word for it."

 => (Peak - RMS) Crest difference = 23.14 dB
 => Difference written in wav-diff.wav (max rel. peak = -57.85 dB)
```
So far all test are within -81 dB which was expected and most likely indicates there is no codegen problem (my confidence  = 90%).

**Pull request closed without merging**
