### PR TITLE
ARM, AArch64 support in allocator

### PR DESCRIPTION
**Pull request by smolt**
Needed version blocks for stack direction.

### CODE REVIEW

**Comment by smolt** [comment]
now you get to add same for other target like PPC!

**Comment by redstar** [comment]
See https://github.com/D-Programming-Language/phobos/pull/4076!

**Comment by smolt** [comment]
nice

**Comment by redstar** [comment]
Everything which can go upstream should go upstream.

**Comment by smolt** [comment]
Seems like a good weekend project to diff ldc with upstream and find those upstream-able changes.

**Pull request merged**
